#!/usr/bin/python

import subprocess
from time import gmtime, strftime
from optparse import OptionParser
import os
import signal
from os.path import expanduser
import time

parser = OptionParser()
parser.add_option("-c","--core",help="cores for the LC application")
parser.add_option("-b","--batch",help="batch application co-running with the LC application,including:cc,correlation,decision_tree,fpgrowth,gradient,kmeans,linear_regression,movielens,naive_bayesian,pagerank,svm,triangle")
parser.add_option("-s","--batchcore",help="cores for the batch application")
parser.add_option("-d","--delay", help = "delay between batch and LC")
(options,args) = parser.parse_args()

current_time = strftime("%Y-%m-%d_%H:%M:%S",gmtime())
home = expanduser("~")
#print home+"/spark_scripts/run_"+options.batch+".sh"
pro = subprocess.Popen([home+"/spark_scripts/run_"+options.batch+".sh",options.batchcore])
time.sleep(int(options.delay))
#subprocess.Popen(["sudo", home+"/scripts/bash_scripts/IntelPerformanceCounterMonitorV2.8/pcm.x","-r","-csv=result.csv","-i=25"])
#time.sleep(int(options.delay))
subprocess.call(["./run_networked.sh", options.core])
subprocess.call(["mv","lats.bin","lats_"+options.core+"_"+options.batch+"_"+options.batchcore])


f = open(options.batch+".pid")
pid = int(f.readline())
#print pid
#print pro.pid
pro.kill()
os.killpg(os.getpgid(pid),signal.SIGTERM)
f.close()
subprocess.call(["rm",options.batch+".pid"])
print("--------------------------------------running finished------------------------------------------------")
